### ISSUE TITLE
collect easter eggs here

### ISSUE THREAD

**Issue by mrzl** [mrzl/LacunaLabOracle#7]

**Comment by mrzl** [comment]
text waving around

**Comment by mrzl** [comment]
matrix style glitch

**Comment by transfluxus** [comment]
flip screen

**Comment by mrzl** [comment]
sometimes randomly talk to the visitor ala
'you bore me, go away.'
'you got something smart to say?'
'what's on your mind?'

**Comment by mrzl** [comment]
kinda outdated
